apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proto-pvc
  namespace: proto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: proto-pv
